name: edu_rev_app
description: A Flutter recreation of the EduRev UKG app

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Update Google Fonts to latest version
  google_fonts: ^6.3.0
  http: ^1.5.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  flutter_hooks: ^0.21.3
  screen_protector: ^1.4.2+1
  pdfx: ^2.9.2
  youtube_player_flutter: ^9.1.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/


